### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sakuya1987** [sakuya1987/protospace-40124#1]
#URL
https://protospace-40124.onrender.com/

**Comment by Akinori0123** [comment]
@sakuya1987 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **(編集機能)バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
編集ページにおいて、一つでも入力に誤りがあると他の入力内容が最初の状態に戻ってしまいますので修正をお願いいたします。
（例えば以下画像のようにプロトタイプ名を変更し、その上でキャッチコピーを空にして保存を押すとプロトタイプ名の変更内容が保存されず最初の状態に戻ってしまいます）
<img width="939" alt="Protospace" src="https://github.com/sakuya1987/protospace-40124/assets/49008705/3e2da021-2528-4af6-9da7-f25998e89e89">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
@sakuya1987 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by sakuya1987** [comment]
ご確認ありがとうございました、最終課題も頑張ります❗️
